version: '2'
services:
  git:
    image: alpine/git
    container_name: rime-git
    restart: always
    volumes:
      - ..:/git
      - .ssh/:/root/.ssh/
      - .gitconfig:/root/.gitconfig
      - .gitignore:/root/.gitignore
    
    working_dir: /git
    entrypoint:
      - sh
      - -c
      - chmod 600 /root/.ssh/id_rsa && git pull origin master && git df --name-status HEAD^ && tail -f /dev/null